def opsworks_cookbook(name, version = '>= 0.0.0', options = {})
  cookbook name, version, { path: "./opsworks-cookbooks/#{name}" }.merge(options)
end

site :opscode

metadata

opsworks_cookbook
    opsworks_initial_setup
    ssh_host_keys
    ssh_users
    mysql::client
    dependencies
    ebs
    opsworks_ganglia::client
    opsworks_nodejs
